import type { Metadata } from "next";
import { site } from "@/content/site";

/**
 * Per-page search/share metadata: canonical URL plus the Open Graph fields
 * link previews use. Paths are relative; `metadataBase` (root layout) makes
 * them absolute. The share image is generated by app/opengraph-image.tsx;
 * it's referenced explicitly because a page's own `openGraph` replaces the
 * one inherited from the root segment, image included.
 */
const shareImage = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${site.name} — ${site.statement}`,
};

export function pageMetadata({
  title,
  description,
  path,
}: {
  /** Page title without the site name; omit for the homepage. */
  title?: string;
  description: string;
  path: string;
}): Metadata {
  const fullTitle = title ? `${title} — ${site.name}` : `${site.name} — ${site.statement}`;
  return {
    ...(title && { title }),
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      siteName: site.name,
      locale: "en_US",
      title: fullTitle,
      description,
      url: path,
      images: [shareImage],
    },
    twitter: { card: "summary_large_image", title: fullTitle, description, images: [shareImage] },
  };
}
